name: try-jupyter
channels:
- conda-forge
dependencies:
- python =3.11
- pip
- mamba
- jupyterlab 
- jupyterlite-core
# at least one kernel for working with notebooks:
- jupyterlite-pyodide-kernel
- jupyterlite-javascript-kernel

# interactivity
- ipywidgets
- ipyevents
- ipycanvas
- ipyleaflet

# plotting
- ipympl
- matplotlib
- plotly

# math/high school algebra
- sympy

# data analysis
- pandas
- numpy
- statsmodels
- scipy
- scikit-learn
- pip:
  - jupyterlite-xeus-sqlite==0.2.1
