name: jptlite-kernels
channels:
- conda-forge
dependencies:
- jupyterlite-core
- jupyterlab
- jupyterlite-pyodide-kernel
- jupyterlite-javascript-kernel
# interactivity
- ipywidgets
- ipyevents
- ipycanvas
- ipyleaflet
# plotting
- ipympl
- matplotlib
# math/high school algebra
- sympy
# data analysis
- pandas
- numpy
- pip:
  - jupyterlite-xeus-sqlite
