name: try-jupyter
channels:
- conda-forge
dependencies:
- python =3.11
- mamba
- ipywidgets >=8.1.1,<9
- jupyterlab >=4.2.5,<=4.3
- notebook >=7.2.2,<7.3
- jupyterlab-night
- jupyterlite-core =0.4.1
- jupyterlite-pyodide-kernel =0.4.2
- jupyterlite-javascript-kernel==0.3.0
- ipympl >=0.8.2
