{
  "STATUS": "THIS CONIFG IS NOT BEING PICKED BY jupyter lite build"
  "LiteBuildConfig": {
    "no_sourcemaps": true,
    "no_unused_shared_packages": true,
    "apps": ["edit","console","notebook","tree","lab","repl"],
    "contents": ["content"]
  }
}
